CREATE TABLE IF NOT EXISTS usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    usuario VARCHAR(50) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO usuarios (usuario, senha) VALUES (
    'visitas',
    '$2y$10$G9f5G9cbYUKezBsoFmRPu.9/17wUSB5lqUVdqEtU1kUkDcYYoN7hG'
);
